name: pos_pinch_zoom_image_example
description: Demonstrates how to use the pinch_zoom_image plugin.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pos_pinch_zoom_image:
    path: ../

flutter:
  uses-material-design: true
  assets:
   - images/camel.jpg
